---
os: linux
dist: focal
language: rust
cache: cargo
rust:
  - 1.45.2


jobs:
  include:
    - stage: build
      before_script:
        - rustup component add rustfmt
        - rustup component add clippy
      # As a result of https://github.com/travis-ci/travis-ci/issues/1066, we run
      # everything in one large command instead of multiple commands.
      # In this way, the build stops immediately if one of the commands fails.
      script: |
        cargo fmt --all -- --check &&
        cargo clippy -- -D warnings &&
        cargo build &&
        cargo test
    - stage: build
      services:
        - docker
      script:
        - export SHORT_TAG=$(git rev-parse --short ${TRAVIS_COMMIT})
        - docker build -t liftright-data-server -f Dockerfile .
        - docker tag liftright-data-server ${TRAVIS_BRANCH}-${SHORT_TAG}
      deploy:
        - provider: script
          edge: true
          script:
            - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
            - docker push alexlauni/liftright-data-server
          on:
            all_branches: true
        - provider: script
          edge: true
          script:
            - echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
            - docker push alexlauni/liftright-data-server
            - docker tag liftright-data-server ${SHORT_TAG}
          on:
            branch: main
    - stage: benchmark
      language: python
      python:
        - "3.8"
      before_install:
        - pip install pipenv
        - git clone https://github.com/wg/wrk.git wrk &&
          cd wrk &&
          make &&
          mv wrk ~/bin &&
          cd ..
      install:
        - git clone https://launibot:${GH_TOKEN}@github.com/LiftRight/lrds-bench
        - cd lrds-bench
        - docker-compose -f mongo-compose.yaml up -d
        - pipenv install
      script:
        - export BRANCH_TAG=${TRAVIS_BRANCH}-$(git rev-parse --short ${TRAVIS_COMMIT})
        - >-
          git clone --single-branch --branch=gh-pages
            https://github.com/lamalex/liftright-data-server.git output
        - pipenv run python bench-tags.py --runs=1 --on-tag=${BRANCH_TAG} --output=output
      after_script:
        - >-
          docker run --rm -it lumir/remove-dockerhub-tag
            --user ${DOCKER_USERNAME}
            --password ${DOCKER_PASSWORD}
            ${DOCKER_USERNAME}/liftright-data-server:${BRANCH_TAG}
      deploy:
        provider: pages
        edge: true
        strategy: git
        token: ${GH_TOKEN}
        local_dir: output
        cleanup: false
        on:
          all_branches: true
    - stage: rollout
      if: branch = main
      before_install:
        - curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash &&
          mv kustomize ~/bin
      script: |
        export SHORT_TAG=$(git rev-parse --short ${TRAVIS_COMMIT}) &&
        git clone https://github.com/LiftRight/lrds-deploy.git &&
        cd lrds-deploy/lrds/overlays/staging &&
        kustomize edit set image alexlauni/liftright-data-server=alexlauni/liftright-data-server:${SHORT_TAG} &&
        git commit kustomization.yaml -m "Update staging docker image to ${SHORT_TAG}" &&
        git remote set-url origin https://launibot:${GH_TOKEN}@github.com/LiftRight/lrds-deploy.git &&
        git push origin main
