---
dist: focal
language: rust
cache: cargo
rust:
  - 1.45.2

services:
  - docker

before_install: |
  LATEST_KUBE_VERSION=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt) &&
  curl -LO "https://storage.googleapis.com/kubernetes-release/release/${LATEST_KUBE_VERSION}/bin/linux/amd64/kubectl" && 
  chmod +x kubectl && mkdir -p ~/bin && mv kubectl ~/bin 

before_script:
- rustup component add rustfmt
- rustup component add clippy

# As a result of https://github.com/travis-ci/travis-ci/issues/1066, we run
# everything in one large command instead of multiple commands.
# In this way, the build stops immediately if one of the commands fails.
script: |
  cargo fmt --all -- --check &&
  cargo clippy -- -D warnings &&
  cargo build &&
  cargo test &&
  docker build -t alexlauni/liftright-data-server:$(git rev-parse --short ${TRAVIS_COMMIT}) \
    -t alexlauni/liftright-data-server:latest -f Dockerfile .

deploy:
  provider: script
  script:
    - docker login -u ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
    - docker push alexlauni/liftright-data-server
  on:
    branch: main

after_deploy: |
  export NEW_IMAGE="alexlauni/liftright-data-server:$(git rev-parse --short ${TRAVIS_COMMIT})" &&
  git clone https://github.com/LiftRight/lrds-deploy &&
  cd lrds-deploy/lrds/bases/backend/ &&
  ~/bin/kubectl patch --local \
    -o yaml \
    -f deployment.yaml \
    -p "spec:
          template:
            spec:
              containers:
                - name: lrds
                  image: ${NEW_IMAGE}" \
    > /tmp/newdeployment.yaml &&
   mv /tmp/newdeployment.yaml deployment.yaml &&
   git commit deployment.yaml -m "Update docker image to ${NEW_IMAGE}" &&
   git push origin main
