language: rust
rust:
  - stable

cache: cargo

services:
  - docker

script:
  - docker build -t alexlauni/liftright-data-server -f Dockerfile . 
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" == "main" ]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; docker push alexlauni/liftright-data-server; fi'

