[package]
name = "liftright-data-server"
version = "0.1.0"
authors = ["Alexander Launi <alaun001@odu.edu>"]
edition = "2018"

[dependencies]
warp = "0.2"
parking_lot = "0.10.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = ["macros"] }
diesel = { version = "1.4", features = ["postgres", "uuid", "chrono", "serde_json", "numeric"] }
dotenv = "0.15.0"
uuid = ">=0.2.0, <0.7.0"
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
serde_derive = "1.0"
log = "0.4"
pretty_env_logger = "0.4"